name: "auth"

runs:
  using: "composite"
  steps:
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v2'
        with:
          workload_identity_provider: 'projects/38617274160/locations/global/workloadIdentityPools/test/providers/github'
          service_account: 'github@idyllic-aspect-442902-h0.iam.gserviceaccount.com'
