name: "deploy"

runs:
  using: "composite"
  steps:
      - name: Setup terraform
        uses: hashicorp/setup-terraform@v2
        
      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Apply
        run: terraform apply