name: "plan"
inputs:
  directory:
    description: 'The target directory to plan'
    required: true
runs:
  using: "composite"
  steps:
      - name: Setup terraform
        uses: hashicorp/setup-terraform@v2
      - name: Change directory
        shell: bash
        run: cd ${{ inputs.directory }}
      - name: check
        shell: bash
        run: pwd
      - name: Terraform Init
        shell: bash
        run: terraform init
      - name: Terraform plan
        shell: bash
        run: terraform plan