name: "plan"

runs:
  using: "composite"
  steps:
      - name: check
        shell: bash
        run: pwd
      - name: Setup terraform
        uses: hashicorp/setup-terraform@v2
      - name: Terraform Init
        shell: bash
        run: terraform init
      - name: Terraform plan
        shell: bash
        run: terraform plan