name: test
on:
  pull_request:
    paths:
      - 'a/**'
  push:
    paths:
      - 'a/**'

jobs:
  plan:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - uses: ./.github/actions/auth
      - uses: ./.github/actions/plan
      with:
        directory: 'a'


  deploy:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - uses: ./.github/actions/auth
      - name: Change directory
        run: cd a
      - uses: ./.github/actions/deploy
        with:
          directory: 'a'
