name: gcloud
on:
  push:

jobs:
  gcloud:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - uses: ./.github/actions/auth
      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'
        with:
          version: '>= 363.0.0'

      - name: 'Use gcloud CLI'
        run: gcloud auth print-access-token
      # - name: Change directory
      #   run: cd a
      # - uses: ./.github/actions/deploy
      #   with:
      #     directory: 'a'
